# This workflow is triggered every time you push to the main branch
name: Promote to Test Stage

on:
  push:
    branches:
      - main  # Only run this workflow on pushes to the main branch

jobs:
  promote-to-test:
    runs-on: ubuntu-latest  # Use the latest stable Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Make sure this version exists on GitHub (this one does!)

      # Step 3: Install dependencies listed in requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Only install dependencies if requirements.txt exists
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run your script to simulate promoting to the Test stage
      - name: Run promotion script
        run: |
          echo "🚀 Promoting application to the Test stage..."
          python dev/app.py  # Make sure this is the correct script path
