# This GitHub Action automates the process of simulating code promotion to the "Test" environment
name: Promote to Test Stage

# Trigger the workflow every time code is pushed to the main branch
on:
  push:
    branches:
      - main  # You can change this if your dev branch has a different name

jobs:
  promote-to-test:
    runs-on: ubuntu-latest  # This job runs on a virtual Ubuntu machine

    steps:
      # Step 1: Checkout the repository code so it can be used in the workflow
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # You can change this to match your project's version

      # Step 3: Install all dependencies listed in requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Ensure pip is up-to-date
          pip install -r requirements.txt      # Install dependencies for the project

      # Step 4: Simulate promotion to the Test environment
      - name: Run promotion logic
        run: |
          echo "✅ Code successfully promoted to the Test stage."
          echo "Simulating integration tests, static checks, or validations..."